default: &default
  adapter:  postgresql
  encoding: unicode
  pool:     5

development:
  <<: *default
  database: hackkings_now_development

test:
  <<: *default
  database: hackkings_now_test

production:
  <<: *default
  database: hackkings_now_production
